# Generated by Django 4.2 on 2024-02-28 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField(verbose_name='Дата раздачи')),
                ('start_time', models.TimeField(verbose_name='Начало раздачи')),
                ('end_time', models.TimeField(verbose_name='Окончание раздачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Раздача',
                'verbose_name_plural': 'Раздачи',
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название газеты')),
            ],
            options={
                'verbose_name': 'Газета',
                'verbose_name_plural': 'Газеты',
            },
        ),
        migrations.CreateModel(
            name='NewspaperNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('year', models.DateField(blank=True, null=True, verbose_name='Год и месяц выхода')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='press.newspaper', verbose_name='Газета')),
            ],
            options={
                'verbose_name': 'Номер газеты',
                'verbose_name_plural': 'Номера газет',
            },
        ),
        migrations.CreateModel(
            name='Sympathizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сочувствующего')),
            ],
            options={
                'verbose_name': 'Сочувствующий',
                'verbose_name_plural': 'Сочувствующие',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='NewspaperNumbersOnDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='press.distribution', verbose_name='Раздача')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='press.newspapernumber', verbose_name='Номер газеты')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование предприятия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('geo_lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('geo_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factories', to='press.town', verbose_name='Город расположения')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='DistributionSympathizerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sympathizer_members', to='press.distribution', verbose_name='Раздача')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='press.sympathizer', verbose_name='Раздающий сочувствующий')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionPartyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_members', to='press.distribution', verbose_name='Раздача')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to=settings.AUTH_USER_MODEL, verbose_name='Раздающий')),
            ],
        ),
        migrations.AddField(
            model_name='distribution',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='press.factorypoint', verbose_name='Предприятие'),
        ),
    ]
