# Generated by Django 4.2 on 2024-03-23 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='short_title',
            field=models.CharField(default='НП', max_length=10, verbose_name='Краткое название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspapernumber',
            name='newspaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newspaper', to='press.newspaper', verbose_name='Газета'),
        ),
    ]
